"""Device-level knobs for the TRAINING paths only, both OPT-IN.

`enable_tf32`  lets fp32 matmuls run on the tensor cores. On Ampere and
               later that is the difference between the fp32 and the
               TF32 rate for every matmul the trainer does outside an
               autocast block, which on the imitation trainer's default
               path is all of them.
`adamw`        the fused optimizer kernel on request, which folds the
               whole step into one launch instead of one per tensor.

Both change the arithmetic of a training run (TF32 rounds the matmul
inputs to 10 mantissa bits; the fused step sums in another order), so
neither is a default: a run that turns one on is a one-factor change
with its own match (the standing rule in docs/plan_20260904.md). The
switches are `supervised_train --tf32 / --fused-adamw` and
`az_loop --tf32`; the trainer's own holdout probe runs under whatever
the run chose, so a TF32 run's holdout numbers are TF32 numbers.

The simulator, the corpus sweeps and eval matches never call this
module (tests/test_train_perf.py pins that); only the matmul switch is
touched, never cuDNN's, which this model does not use.
"""
from __future__ import annotations

import contextlib
import logging
from typing import Dict, Iterable

import torch

log = logging.getLogger("train_perf")

_LOGGED = False


def enable_tf32(enable: bool = True, *, quiet: bool = False) -> Dict[str, bool]:
    """Turn TF32 on (or off) for fp32 matmuls. Returns the setting as
    it was before, so a caller can restore it. A no-op without CUDA.
    cuDNN's own TF32 switch (torch's default: on) is left alone."""
    global _LOGGED
    before = {"matmul": bool(torch.backends.cuda.matmul.allow_tf32)}
    if not torch.cuda.is_available():
        return before
    torch.backends.cuda.matmul.allow_tf32 = bool(enable)
    if enable and not _LOGGED and not quiet:
        _LOGGED = True
        log.info("TF32 on for fp32 matmuls (this training run's choice; "
                 "the sim, the corpus sweeps and eval are untouched)")
    return before


@contextlib.contextmanager
def tf32_training(enable: bool = True):
    """TF32 for the block when `enable`, restored afterwards.

    Use this, not the bare `enable_tf32`, in any process that ALSO
    serves inference: `tools/az_loop.py` runs the learner and an
    in-process inference server in one process, and a global switch
    would quietly put the actors' leaf evaluations on 10-bit matmuls
    while the serve processes it spawns stayed on fp32 -- one
    iteration's self-play data generated by two different numerics.
    """
    if not enable:
        yield
        return
    before = enable_tf32(True, quiet=True)
    try:
        yield
    finally:
        if torch.cuda.is_available():
            torch.backends.cuda.matmul.allow_tf32 = before["matmul"]


def adamw(params: Iterable[torch.nn.Parameter], *, lr: float,
          weight_decay: float = 0.0, fused: bool = False,
          **kw) -> torch.optim.AdamW:
    """`torch.optim.AdamW`; with `fused=True` the fused kernel when it
    applies (every parameter on CUDA and floating point), else the
    reference step, which is also what a torch too old for the
    argument gets."""
    params = list(params)
    if fused:
        fused = bool(params) and all(p.is_cuda and p.is_floating_point() for p in params)
    if not fused:
        return torch.optim.AdamW(params, lr=lr, weight_decay=weight_decay, **kw)
    try:
        return torch.optim.AdamW(params, lr=lr, weight_decay=weight_decay,
                                 fused=True, **kw)
    except (TypeError, RuntimeError) as exc:      # old torch, or an unsupported dtype
        log.debug("fused AdamW unavailable (%s); using the reference step", exc)
        return torch.optim.AdamW(params, lr=lr, weight_decay=weight_decay, **kw)


def reassert_step_kernel(opt: torch.optim.Optimizer) -> None:
    """After `opt.load_state_dict(...)`: the checkpoint's param groups
    replace the live ones, `fused` included, so a resumed run would
    silently take the checkpoint's step kernel (the reference one for
    every checkpoint written before 2026-09-13, or a fused one on a
    device that has none). Put back what this optimizer was built
    with."""
    if "fused" not in opt.defaults:
        return
    for group in opt.param_groups:
        group["fused"] = opt.defaults["fused"]


__all__ = ["enable_tf32", "tf32_training", "adamw", "reassert_step_kernel"]
