"""Export a simulated game as a Wesnoth-loadable replay (.bz2).

Why: lets the user inspect simulated games directly in Wesnoth's GUI
to validate that the simulator's behavior matches Wesnoth's. Open the
exported file via Wesnoth's main menu -> Load Game -> Replays.

Strategy: a replay file is bz2-compressed WML. After
`[/scenario]` Wesnoth has a `[multiplayer]` block, optional
`[modification]`s, then a final `[replay]` block holding the command
stream. We take a SOURCE replay's bz2 (used as the scenario template,
since the simulator's initial state was built from it), strip the
final `[replay]`, and append our own command stream from the
simulator's `command_history`.

Caveats / known compromises:
- We don't emit `[checkup]` blocks (Wesnoth uses these to detect OOS
  on rejoin; absent on local replay playback Wesnoth will compute
  results from scratch).
- We DO emit `[random_seed]` dependent commands after each recruit /
  attack -- Wesnoth's replay engine requires them ("found [recruit]
  command in replay expecting a user choice" if missing). The seed
  itself is just an 8-hex-char value generated by the exporter; on
  playback Wesnoth uses it to roll traits / damage. Different seeds
  than the sim used internally, so per-strike hit/miss / trait rolls
  on playback will differ from the sim. Unit positions, turn
  structure, and which actions happened remain correct.
- Recruit/recall must include a `[from]` block with the leader's
  keep position; the sim records this at recruit time so the
  exporter doesn't have to reconstruct game state.
- We assume coords in `command_history` are 0-indexed (the sim's
  internal convention -- see replay_dataset.parse_map_data); the
  exporter adds 1 when emitting WML.

CLI usage:
    python tools/sim_to_replay.py SOURCE.bz2 OUT.bz2
    -- self-play one game from SOURCE's initial state (DummyPolicy)
       and write the export to OUT.

Library usage:
    from wesnoth_sim import WesnothSim
    from sim_to_replay import export_replay
    sim = WesnothSim.from_replay("foo.json.gz")
    sim.run_game(p1, p2)
    export_replay(sim, source_bz2="replays_raw/.../foo.bz2",
                  out_path="my_sim.bz2")
"""

from __future__ import annotations

import bz2
import logging
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

# Make project root importable when run as a script.
_THIS = Path(__file__).resolve()
sys.path.insert(0, str(_THIS.parent.parent))
sys.path.insert(0, str(_THIS.parent))

from wesnoth_sim import RecordedCommand, WesnothSim, request_seed


log = logging.getLogger("sim_to_replay")


# ---------------------------------------------------------------------
# WML command emission
# ---------------------------------------------------------------------

def _wml_for_command(rc: RecordedCommand,
                     next_side: Optional[int] = None) -> str:
    """Render one RecordedCommand as a `[command]...[/command]` WML
    block. Coordinates are converted from the sim's 0-indexed
    convention to Wesnoth's 1-indexed WML by adding 1.

    `next_side` is required for end_turn (the side whose init_side
    comes next); it's derived from the history by `_build_replay_wml`.
    """
    if rc.kind == "init_side":
        side_n = rc.cmd[1]
        return (
            "\t[command]\n"
            "\t\t[init_side]\n"
            f"\t\t\tside_number={side_n}\n"
            "\t\t[/init_side]\n"
            "\t[/command]\n"
        )

    if rc.kind == "end_turn":
        # CRITICAL: emit `next_player_number = side + 1`, NOT a
        # modulo'd value. Wesnoth's `skip_empty_sides` decides
        # "is this a new turn?" by checking whether the requested
        # side index changes after modulo wrap-around. If we
        # already wrap (e.g., emit "1" after side 2 in 2p), Wesnoth
        # sees `1 == 1` post-modulo and concludes it's the SAME
        # turn -- so `next_turn()` never fires, `turn_` stays at 1
        # forever, and per-side MP never resets on init_side
        # (the `if (turn() > 1)` check in do_init_side fails).
        # That makes turn 2's first leader move corrupt because
        # the unit still has its leftover MP from turn 1.
        # Real replays emit "3" after side 2's end_turn in 2p; we
        # mirror that pattern here. Caller can override via
        # `next_side` if it has explicit history info, but the
        # default (side+1) is what Wesnoth expects.
        nxt = next_side if next_side is not None else rc.side + 1
        return (
            "\t[command]\n"
            "\t\t[end_turn]\n"
            f"\t\t\tnext_player_number={nxt}\n"
            "\t\t[/end_turn]\n"
            "\t[/command]\n"
        )

    if rc.kind == "move":
        # cmd = ["move", [sx, tx], [sy, ty], from_side]
        xs, ys = rc.cmd[1], rc.cmd[2]
        # Convert to 1-indexed.
        xs1 = ",".join(str(v + 1) for v in xs)
        ys1 = ",".join(str(v + 1) for v in ys)
        return (
            "\t[command]\n"
            f"\t\tfrom_side={rc.side}\n"
            "\t\t[move]\n"
            f"\t\t\tx=\"{xs1}\"\n"
            f"\t\t\ty=\"{ys1}\"\n"
            "\t\t[/move]\n"
            "\t[/command]\n"
        )

    if rc.kind == "attack":
        # cmd = ["attack", ax, ay, dx, dy, a_weapon, d_weapon, seed_hex]
        ax, ay, dx, dy = rc.cmd[1], rc.cmd[2], rc.cmd[3], rc.cmd[4]
        weapon = rc.cmd[5]
        d_weapon = rc.cmd[6] if len(rc.cmd) > 6 else -1
        return (
            "\t[command]\n"
            f"\t\tfrom_side={rc.side}\n"
            "\t\t[attack]\n"
            f"\t\t\tweapon={weapon}\n"
            f"\t\t\tdefender_weapon={d_weapon}\n"
            "\t\t\t[source]\n"
            f"\t\t\t\tx={ax + 1}\n"
            f"\t\t\t\ty={ay + 1}\n"
            "\t\t\t[/source]\n"
            "\t\t\t[destination]\n"
            f"\t\t\t\tx={dx + 1}\n"
            f"\t\t\t\ty={dy + 1}\n"
            "\t\t\t[/destination]\n"
            "\t\t[/attack]\n"
            "\t[/command]\n"
        )

    if rc.kind == "recruit":
        # cmd = ["recruit", unit_type, tx, ty, trait_seed]
        unit_type = rc.cmd[1]
        tx, ty = rc.cmd[2], rc.cmd[3]
        leader_pos = rc.extras.get("leader_pos", (tx, ty))
        lx, ly = leader_pos
        return (
            "\t[command]\n"
            f"\t\tfrom_side={rc.side}\n"
            "\t\t[recruit]\n"
            f"\t\t\ttype=\"{unit_type}\"\n"
            f"\t\t\tx={tx + 1}\n"
            f"\t\t\ty={ty + 1}\n"
            "\t\t\t[from]\n"
            f"\t\t\t\tx={lx + 1}\n"
            f"\t\t\t\ty={ly + 1}\n"
            "\t\t\t[/from]\n"
            "\t\t[/recruit]\n"
            "\t[/command]\n"
        )

    if rc.kind == "recall":
        # cmd = ["recall", unit_id, tx, ty]
        unit_id = rc.cmd[1]
        tx, ty = rc.cmd[2], rc.cmd[3]
        leader_pos = rc.extras.get("leader_pos", (tx, ty))
        lx, ly = leader_pos
        return (
            "\t[command]\n"
            f"\t\tfrom_side={rc.side}\n"
            "\t\t[recall]\n"
            f"\t\t\tvalue=\"{unit_id}\"\n"
            f"\t\t\tx={tx + 1}\n"
            f"\t\t\ty={ty + 1}\n"
            "\t\t\t[from]\n"
            f"\t\t\t\tx={lx + 1}\n"
            f"\t\t\t\ty={ly + 1}\n"
            "\t\t\t[/from]\n"
            "\t\t[/recall]\n"
            "\t[/command]\n"
        )

    log.warning(f"sim_to_replay: skipping unknown command kind: {rc.kind!r}")
    return ""


def _seed_from_recorded(rc: RecordedCommand) -> str:
    """Pull the seed the sim already used for this command. We assume
    the sim populated it via wesnoth_sim.request_seed(N) -- making
    the replay's [random_seed] match what the sim used internally,
    so trait/damage rolls agree bit-exact between sim and Wesnoth."""
    if rc.kind == "recruit":
        # cmd = ["recruit", unit_type, tx, ty, seed]
        return rc.cmd[4] if len(rc.cmd) > 4 and rc.cmd[4] else "00000000"
    if rc.kind == "attack":
        # cmd = ["attack", ax, ay, dx, dy, a_w, d_w, seed]
        return rc.cmd[7] if len(rc.cmd) > 7 and rc.cmd[7] else "00000000"
    return "00000000"


def _wml_random_seed_command(seed: str, request_id: int) -> str:
    """Emit a synthetic `[command] ... [random_seed]` block. Wesnoth's
    replay engine demands one of these after every command that needs
    a random roll (recruit -> trait roll, attack -> damage rolls);
    without them you get 'expecting a user choice' on playback. The
    seed must be the SAME hex value the sim used internally so both
    sides agree on traits / damage.

    Indentation: emitted unindented to match the formatting Wesnoth
    itself produces for dependent commands. WML's parser is supposed
    to be whitespace-insensitive, but matching the real-replay style
    is one less variable when debugging OOS issues."""
    return (
        "[command]\n"
        "dependent=\"yes\"\n"
        "from_side=\"server\"\n"
        "[random_seed]\n"
        f"new_seed=\"{seed}\"\n"
        f"request_id=\"{request_id}\"\n"
        "[/random_seed]\n"
        "[/command]\n"
    )


# Commands that need a [random_seed] follow-up. Verified for recruit
# (trait roll) and attack (damage roll) by inspecting real Wesnoth
# replays. Recall does NOT need one -- recalled units' traits were
# already rolled at recruit time.
_NEEDS_RNG = frozenset({"recruit", "attack"})


def _build_replay_wml(history: List[RecordedCommand]) -> str:
    """Emit `[replay] ... [/replay]` content from a command history.
    After each random-rolling command we emit a synthetic
    `[random_seed]` follow-up so Wesnoth's replay engine has a 'user
    choice' to consume.

    end_turn's `next_player_number` is left unset here so the emitter
    falls back to `rc.side + 1` -- the convention Wesnoth's
    skip_empty_sides expects for detecting turn wrap-around. (Looking
    up the actual next init_side and using that value would emit "1"
    after side 2 in 2p, which Wesnoth treats as 'still on turn 1' --
    breaking turn 2's MP reset.)
    """
    parts: List[str] = []
    request_id = 0
    for rc in history:
        parts.append(_wml_for_command(rc, next_side=None))
        if rc.kind in _NEEDS_RNG:
            request_id += 1
            seed = _seed_from_recorded(rc)
            parts.append(_wml_random_seed_command(seed, request_id))
    return "[replay]\n" + "".join(parts) + "[/replay]\n"


# ---------------------------------------------------------------------
# Source-file splicing
# ---------------------------------------------------------------------

def _find_final_replay_block(text: str) -> Optional[tuple]:
    """Locate the offsets of the final `[replay]...[/replay]` block in
    a decompressed replay file. Returns (start, end) where start is
    the offset of the `[replay]` line and end is just past `[/replay]`.

    The file may have an empty initial `[replay]` block (with just
    `[upload_log]`) before `[scenario]`; we always want the LAST one
    in the file, after `[/scenario]`."""
    # Find every [replay] / [/replay] pair, take the last one.
    last_open = text.rfind("[replay]")
    if last_open < 0:
        return None
    last_close = text.find("[/replay]", last_open)
    if last_close < 0:
        return None
    return (last_open, last_close + len("[/replay]"))


def export_replay(
    sim:        WesnothSim,
    source_bz2: Path,
    out_path:   Path,
) -> None:
    """Write `out_path` (a .bz2) such that Wesnoth can load it as a
    replay reproducing `sim`'s game from its initial state.

    `source_bz2` MUST be the same replay the sim was initialized from
    (via `WesnothSim.from_replay(<json.gz>)`). The .bz2 carries the
    full scenario WML the sim's initial state was derived from --
    map, sides, factions, leader stats. We can't reconstruct that
    from the sim's GameState alone (we'd lose modifications, era
    config, ai settings, mp_era_name, etc.).
    """
    source_bz2 = Path(source_bz2)
    out_path = Path(out_path)
    log.info(f"loading source replay {source_bz2}")
    with bz2.open(source_bz2, "rt", encoding="utf-8", errors="ignore") as f:
        text = f.read()

    span = _find_final_replay_block(text)
    if span is None:
        raise RuntimeError(
            f"{source_bz2}: could not locate final [replay] block. "
            "File doesn't look like a Wesnoth replay.")
    start, end = span

    new_replay = _build_replay_wml(sim.command_history)
    spliced = text[:start] + new_replay + text[end:]

    log.info(f"writing {out_path} ({len(sim.command_history)} commands)")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with bz2.open(out_path, "wt", encoding="utf-8") as f:
        f.write(spliced)


# ---------------------------------------------------------------------
# Source mapping (json.gz <-> .bz2)
# ---------------------------------------------------------------------

def find_source_bz2(json_gz_path: Path,
                    replays_raw: Path = Path("replays_raw")) -> Optional[Path]:
    """Given the path of a `replays_dataset/<id>.json.gz`, find the
    corresponding `replays_raw/<date>/<game_id>.bz2`. Returns None
    if not found (e.g., the user reorganized replays_raw)."""
    import gzip, json
    with gzip.open(json_gz_path, "rt", encoding="utf-8") as f:
        data = json.load(f)
    game_id = data.get("game_id", "")
    if not game_id:
        return None
    # game_id has double-underscore separating prefix from rest, but
    # the .bz2 filename uses the same convention. Try the literal
    # game_id first (matches recent dumps), then the legacy `_-_`
    # variant.
    candidates = [game_id + ".bz2",
                  game_id.replace("__", "_-_", 1) + ".bz2"]
    replays_raw = Path(replays_raw)
    if not replays_raw.exists():
        return None
    for date_dir in sorted(replays_raw.iterdir()):
        if not date_dir.is_dir():
            continue
        for cand in candidates:
            p = date_dir / cand
            if p.exists():
                return p
    return None


# ---------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------

def _cli(argv: List[str]) -> int:
    """`python tools/sim_to_replay.py REPLAY.json.gz OUT.bz2`
    runs a sim from REPLAY's initial state with the dummy policy and
    writes a Wesnoth-loadable replay to OUT.bz2."""
    import argparse
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    ap = argparse.ArgumentParser()
    ap.add_argument("source_json_gz", type=Path,
                    help="replays_dataset/<id>.json.gz to take init from")
    ap.add_argument("out_bz2", type=Path,
                    help="output .bz2 -- e.g., my_sim_run.bz2")
    ap.add_argument("--max-turns", type=int, default=40)
    ap.add_argument("--source-bz2", type=Path, default=None,
                    help="override automatic source-bz2 lookup")
    args = ap.parse_args(argv[1:])

    src_bz2 = args.source_bz2 or find_source_bz2(args.source_json_gz)
    if src_bz2 is None:
        log.error(
            f"could not auto-locate the .bz2 matching "
            f"{args.source_json_gz}. Pass --source-bz2 to override.")
        return 2
    log.info(f"using source bz2: {src_bz2}")

    from dummy_policy import DummyPolicy
    sim = WesnothSim.from_replay(args.source_json_gz, max_turns=args.max_turns)
    res = sim.run_game(DummyPolicy(), DummyPolicy())
    log.info(f"sim done: winner={res.winner} turns={res.turns} "
             f"ended_by={res.ended_by} "
             f"actions s1/s2 = {res.side1_actions}/{res.side2_actions}")

    export_replay(sim, source_bz2=src_bz2, out_path=args.out_bz2)
    log.info(f"wrote {args.out_bz2}")
    return 0


if __name__ == "__main__":
    sys.exit(_cli(sys.argv))
