"""Export a simulated game as a Wesnoth-loadable replay (.bz2).

Why: lets the user inspect simulated games directly in Wesnoth's GUI
to validate that the simulator's behavior matches Wesnoth's. Open the
exported file via Wesnoth's main menu -> Load Game -> Replays.

Strategy: a replay file is bz2-compressed WML. After
`[/scenario]` Wesnoth has a `[multiplayer]` block, optional
`[modification]`s, then a final `[replay]` block holding the command
stream. We take a SOURCE replay's bz2 (used as the scenario template,
since the simulator's initial state was built from it), strip the
final `[replay]`, and append our own command stream from the
simulator's `command_history`.

Caveats / known compromises:
- We don't emit `[checkup]` blocks (Wesnoth uses these to detect OOS
  on rejoin; absent on local replay playback Wesnoth will compute
  results from scratch).
- We DO emit `[random_seed]` dependent commands after each recruit /
  attack -- Wesnoth's replay engine requires them ("found [recruit]
  command in replay expecting a user choice" if missing). The seed
  itself is just an 8-hex-char value generated by the exporter; on
  playback Wesnoth uses it to roll traits / damage. Different seeds
  than the sim used internally, so per-strike hit/miss / trait rolls
  on playback will differ from the sim. Unit positions, turn
  structure, and which actions happened remain correct.
- Recruit/recall must include a `[from]` block with the leader's
  keep position; the sim records this at recruit time so the
  exporter doesn't have to reconstruct game state.
- We assume coords in `command_history` are 0-indexed (the sim's
  internal convention -- see replay_dataset.parse_map_data); the
  exporter adds 1 when emitting WML.

CLI usage:
    python tools/sim_to_replay.py SOURCE.bz2 OUT.bz2
    -- self-play one game from SOURCE's initial state (DummyPolicy)
       and write the export to OUT.

Library usage:
    from wesnoth_sim import WesnothSim
    from sim_to_replay import export_replay
    sim = WesnothSim.from_replay("foo.json.gz")
    sim.run_game(p1, p2)
    export_replay(sim, source_bz2="replays_raw/.../foo.bz2",
                  out_path="my_sim.bz2")
"""

from __future__ import annotations

import bz2
import logging
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

# Make project root importable when run as a script.
_THIS = Path(__file__).resolve()
sys.path.insert(0, str(_THIS.parent.parent))
sys.path.insert(0, str(_THIS.parent))

from wesnoth_sim import PvPDefaults, RecordedCommand, WesnothSim, request_seed


log = logging.getLogger("sim_to_replay")


# ---------------------------------------------------------------------
# WML command emission
# ---------------------------------------------------------------------

def _wml_for_command(rc: RecordedCommand,
                     next_side: Optional[int] = None) -> str:
    """Render one RecordedCommand as a `[command]...[/command]` WML
    block. Coordinates are converted from the sim's 0-indexed
    convention to Wesnoth's 1-indexed WML by adding 1.

    `next_side` is required for end_turn (the side whose init_side
    comes next); it's derived from the history by `_build_replay_wml`.
    """
    if rc.kind == "init_side":
        side_n = rc.cmd[1]
        return (
            "\t[command]\n"
            "\t\t[init_side]\n"
            f"\t\t\tside_number={side_n}\n"
            "\t\t[/init_side]\n"
            "\t[/command]\n"
        )

    if rc.kind == "end_turn":
        # CRITICAL: emit `next_player_number = side + 1`, NOT a
        # modulo'd value. Wesnoth's `skip_empty_sides` decides
        # "is this a new turn?" by checking whether the requested
        # side index changes after modulo wrap-around. If we
        # already wrap (e.g., emit "1" after side 2 in 2p), Wesnoth
        # sees `1 == 1` post-modulo and concludes it's the SAME
        # turn -- so `next_turn()` never fires, `turn_` stays at 1
        # forever, and per-side MP never resets on init_side
        # (the `if (turn() > 1)` check in do_init_side fails).
        # That makes turn 2's first leader move corrupt because
        # the unit still has its leftover MP from turn 1.
        # Real replays emit "3" after side 2's end_turn in 2p; we
        # mirror that pattern here. Caller can override via
        # `next_side` if it has explicit history info, but the
        # default (side+1) is what Wesnoth expects.
        nxt = next_side if next_side is not None else rc.side + 1
        return (
            "\t[command]\n"
            "\t\t[end_turn]\n"
            f"\t\t\tnext_player_number={nxt}\n"
            "\t\t[/end_turn]\n"
            "\t[/command]\n"
        )

    if rc.kind == "move":
        # cmd = ["move", [sx, tx], [sy, ty], from_side]
        xs, ys = rc.cmd[1], rc.cmd[2]
        # Convert to 1-indexed.
        xs1 = ",".join(str(v + 1) for v in xs)
        ys1 = ",".join(str(v + 1) for v in ys)
        return (
            "\t[command]\n"
            f"\t\tfrom_side={rc.side}\n"
            "\t\t[move]\n"
            f"\t\t\tx=\"{xs1}\"\n"
            f"\t\t\ty=\"{ys1}\"\n"
            "\t\t[/move]\n"
            "\t[/command]\n"
        )

    if rc.kind == "attack":
        # cmd = ["attack", ax, ay, dx, dy, a_weapon, d_weapon, seed_hex]
        ax, ay, dx, dy = rc.cmd[1], rc.cmd[2], rc.cmd[3], rc.cmd[4]
        weapon = rc.cmd[5]
        d_weapon = rc.cmd[6] if len(rc.cmd) > 6 else -1
        return (
            "\t[command]\n"
            f"\t\tfrom_side={rc.side}\n"
            "\t\t[attack]\n"
            f"\t\t\tweapon={weapon}\n"
            f"\t\t\tdefender_weapon={d_weapon}\n"
            "\t\t\t[source]\n"
            f"\t\t\t\tx={ax + 1}\n"
            f"\t\t\t\ty={ay + 1}\n"
            "\t\t\t[/source]\n"
            "\t\t\t[destination]\n"
            f"\t\t\t\tx={dx + 1}\n"
            f"\t\t\t\ty={dy + 1}\n"
            "\t\t\t[/destination]\n"
            "\t\t[/attack]\n"
            "\t[/command]\n"
        )

    if rc.kind == "recruit":
        # cmd = ["recruit", unit_type, tx, ty, trait_seed]
        unit_type = rc.cmd[1]
        tx, ty = rc.cmd[2], rc.cmd[3]
        leader_pos = rc.extras.get("leader_pos", (tx, ty))
        lx, ly = leader_pos
        return (
            "\t[command]\n"
            f"\t\tfrom_side={rc.side}\n"
            "\t\t[recruit]\n"
            f"\t\t\ttype=\"{unit_type}\"\n"
            f"\t\t\tx={tx + 1}\n"
            f"\t\t\ty={ty + 1}\n"
            "\t\t\t[from]\n"
            f"\t\t\t\tx={lx + 1}\n"
            f"\t\t\t\ty={ly + 1}\n"
            "\t\t\t[/from]\n"
            "\t\t[/recruit]\n"
            "\t[/command]\n"
        )

    if rc.kind == "recall":
        # cmd = ["recall", unit_id, tx, ty]
        unit_id = rc.cmd[1]
        tx, ty = rc.cmd[2], rc.cmd[3]
        leader_pos = rc.extras.get("leader_pos", (tx, ty))
        lx, ly = leader_pos
        return (
            "\t[command]\n"
            f"\t\tfrom_side={rc.side}\n"
            "\t\t[recall]\n"
            f"\t\t\tvalue=\"{unit_id}\"\n"
            f"\t\t\tx={tx + 1}\n"
            f"\t\t\ty={ty + 1}\n"
            "\t\t\t[from]\n"
            f"\t\t\t\tx={lx + 1}\n"
            f"\t\t\t\ty={ly + 1}\n"
            "\t\t\t[/from]\n"
            "\t\t[/recall]\n"
            "\t[/command]\n"
        )

    log.warning(f"sim_to_replay: skipping unknown command kind: {rc.kind!r}")
    return ""


def _seed_from_recorded(rc: RecordedCommand) -> str:
    """Pull the seed the sim already used for this command. We assume
    the sim populated it via wesnoth_sim.request_seed(N) -- making
    the replay's [random_seed] match what the sim used internally,
    so trait/damage rolls agree bit-exact between sim and Wesnoth."""
    if rc.kind == "recruit":
        # cmd = ["recruit", unit_type, tx, ty, seed]
        return rc.cmd[4] if len(rc.cmd) > 4 and rc.cmd[4] else "00000000"
    if rc.kind == "attack":
        # cmd = ["attack", ax, ay, dx, dy, a_w, d_w, seed]
        return rc.cmd[7] if len(rc.cmd) > 7 and rc.cmd[7] else "00000000"
    return "00000000"


# ---------------------------------------------------------------------
# RNG-consumption gating
# ---------------------------------------------------------------------
# Wesnoth's synced_rng is LAZY: the seed from `[random_seed]` is only
# fetched on the FIRST `get_next_random()` call inside a synced
# command (see wesnoth_src/src/random_synced.cpp:31-49). If a recruit
# never calls RNG -- e.g. Skeleton (musthave=['undead'], num_traits=1,
# pool_size=0, single-gender) -- the seed is never fetched. Our
# `[random_seed]` follow-up is then orphaned: the outer replay loop
# sees a `dependent="yes"` command while is_unsynced=true and fires
# "found dependent command in replay while is_synced=false".
#
# So we have to predict whether each synced command consumes RNG and
# only emit `[random_seed]` for those that do. Real Wesnoth replays
# do this implicitly because the seed-write only happens when the
# server actually generated a seed.

_RNG_INFO_CACHE: Dict[str, dict] = {}


def _unit_trait_info(unit_type: str) -> dict:
    """Return the trait/gender info we need to predict synced RNG
    consumption for a recruit. Returns {} on lookup failure."""
    if unit_type in _RNG_INFO_CACHE:
        return _RNG_INFO_CACHE[unit_type]
    try:
        import json
        path = Path(__file__).resolve().parent.parent / "unit_stats.json"
        with path.open(encoding="utf-8") as f:
            data = json.load(f)
        u = data.get("units", {}).get(unit_type, {})
        t = u.get("traits", {}) or {}
        info = {
            "n_genders":  int(u.get("n_genders", 1)),
            "num_traits": int(t.get("num_traits", 2)),
            "musthave":   list(t.get("musthave", [])),
            "pool":       list(t.get("pool", [])),
        }
        _RNG_INFO_CACHE[unit_type] = info
        return info
    except Exception:
        _RNG_INFO_CACHE[unit_type] = {}
        return {}


def _recruit_consumes_synced_rng(unit_type: str) -> bool:
    """True iff Wesnoth's recruit handler calls `get_random_int` for
    this unit type, which is the trigger for `synced_rng::initialize`
    fetching the [random_seed] payload.

    Wesnoth's order in `unit::init` (wesnoth_src/src/units/unit.cpp:714):
      1. generate_gender -- one synced RNG call iff genders.size() > 1
         (single-gender unit_types like Skeleton short-circuit and
         consume zero).
      2. facing_ -- uses default_instance() (NON-synced); doesn't
         touch our seed.
      3. advance_to -> generate_traits -- per missing trait beyond
         musthaves, one synced call to pick from the available pool.
         If musthaves already fill num_traits OR the pool is empty
         after filtering, the for-loop never enters.
    """
    info = _unit_trait_info(unit_type)
    if not info:
        # Unknown unit type -- be conservative and emit the seed.
        # Worst case Wesnoth ignores it; missing seed produces the
        # actual OOS we're trying to fix.
        return True
    if info["n_genders"] > 1:
        return True
    n_random = max(0, info["num_traits"] - len(info["musthave"]))
    if n_random <= 0:
        return False
    # If pool minus already-applied musthaves is empty, the loop
    # exits via the `if(candidate_traits.empty()) break` branch
    # without calling RNG.
    available = [t for t in info["pool"] if t not in info["musthave"]]
    return len(available) > 0


def _command_consumes_synced_rng(rc: RecordedCommand) -> bool:
    """Whether a recorded command's Wesnoth-side execution calls
    synced RNG (and thus should receive a [random_seed] follow-up).
    Recruit: depends on unit type (see _recruit_consumes_synced_rng).
    Attack: always (combat rolls every strike's hit/miss).
    Other kinds: never (caller doesn't reach here)."""
    if rc.kind == "recruit":
        unit_type = rc.cmd[1] if len(rc.cmd) > 1 else ""
        return _recruit_consumes_synced_rng(unit_type)
    if rc.kind == "attack":
        return True
    return False


def _wml_choose_command(side: int, value: int) -> str:
    """Emit a synthetic `[command] dependent="yes" [choose]` block --
    Wesnoth's record of an advancement choice. After every attack that
    levels up the attacker and/or defender, `attack_unit_and_advance`
    (wesnoth_src/src/actions/attack.cpp:1556-1573) calls
    `advance_unit_at` per advancing unit, which goes through
    `mp_sync::get_user_choice("choose", ...)`. The replay records the
    chosen advancement index here. Without these, replay playback
    errors with "expecting a user choice" the first time a unit levels
    up mid-battle.

    Order in the WML stream MUST be: attack [command], its
    [random_seed] follow-up, then attacker's [choose] (if attacker
    advanced), then defender's [choose] (if defender advanced).

    Format mirrors a real-replay sample (`from_side` is the unit's
    OWNER side, not "server" -- different from [random_seed] which is
    server-emitted)."""
    return (
        "[command]\n"
        "dependent=\"yes\"\n"
        f"from_side=\"{side}\"\n"
        "[choose]\n"
        f"value=\"{value}\"\n"
        "[/choose]\n"
        "[/command]\n"
    )


def _wml_random_seed_command(seed: str, request_id: int) -> str:
    """Emit a synthetic `[command] ... [random_seed]` block. Wesnoth's
    replay engine demands one of these after every command that needs
    a random roll (recruit -> trait roll, attack -> damage rolls);
    without them you get 'expecting a user choice' on playback. The
    seed must be the SAME hex value the sim used internally so both
    sides agree on traits / damage.

    Indentation: emitted unindented to match the formatting Wesnoth
    itself produces for dependent commands. WML's parser is supposed
    to be whitespace-insensitive, but matching the real-replay style
    is one less variable when debugging OOS issues."""
    return (
        "[command]\n"
        "dependent=\"yes\"\n"
        "from_side=\"server\"\n"
        "[random_seed]\n"
        f"new_seed=\"{seed}\"\n"
        f"request_id=\"{request_id}\"\n"
        "[/random_seed]\n"
        "[/command]\n"
    )


# Commands that need a [random_seed] follow-up. Verified for recruit
# (trait roll) and attack (damage roll) by inspecting real Wesnoth
# replays. Recall does NOT need one -- recalled units' traits were
# already rolled at recruit time.
_NEEDS_RNG = frozenset({"recruit", "attack"})


def _build_replay_wml(history: List[RecordedCommand]) -> str:
    """Emit `[replay] ... [/replay]` content from a command history.
    After each random-rolling command we emit a synthetic
    `[random_seed]` follow-up so Wesnoth's replay engine has a 'user
    choice' to consume.

    end_turn's `next_player_number` is left unset here so the emitter
    falls back to `rc.side + 1` -- the convention Wesnoth's
    skip_empty_sides expects for detecting turn wrap-around. (Looking
    up the actual next init_side and using that value would emit "1"
    after side 2 in 2p, which Wesnoth treats as 'still on turn 1' --
    breaking turn 2's MP reset.)
    """
    parts: List[str] = []
    request_id = 0
    for rc in history:
        parts.append(_wml_for_command(rc, next_side=None))
        # Only emit [random_seed] for commands Wesnoth's synced_rng
        # will actually consume. Skeleton-class recruits with no
        # random traits never call get_next_random; emitting a
        # dangling [random_seed] for them produces "found dependent
        # command in replay while is_synced=false" on the NEXT
        # outer-loop iteration.
        if rc.kind in _NEEDS_RNG and _command_consumes_synced_rng(rc):
            request_id += 1
            seed = _seed_from_recorded(rc)
            parts.append(_wml_random_seed_command(seed, request_id))
        # Advancement [choose] follow-ups: emitted AFTER the attack's
        # [random_seed] so the order matches Wesnoth's
        # `attack_unit_and_advance` path (attack -> RNG follow-up ->
        # advancer per side, attacker first then defender). Sim's
        # `_maybe_advance_unit` always picks targets[0], so value=0.
        if rc.kind == "attack":
            for side, idx in rc.extras.get("advance_choices", []):
                parts.append(_wml_choose_command(side, idx))
    return "[replay]\n" + "".join(parts) + "[/replay]\n"


# ---------------------------------------------------------------------
# Source-file splicing
# ---------------------------------------------------------------------

def _find_final_replay_block(text: str) -> Optional[tuple]:
    """Locate the offsets of the final `[replay]...[/replay]` block in
    a decompressed replay file. Returns (start, end) where start is
    the offset of the `[replay]` line and end is just past `[/replay]`.

    The file may have an empty initial `[replay]` block (with just
    `[upload_log]`) before `[scenario]`; we always want the LAST one
    in the file, after `[/scenario]`."""
    # Find every [replay] / [/replay] pair, take the last one.
    last_open = text.rfind("[replay]")
    if last_open < 0:
        return None
    last_close = text.find("[/replay]", last_open)
    if last_close < 0:
        return None
    return (last_open, last_close + len("[/replay]"))


def _rewrite_pvp_settings(text: str, defaults: PvPDefaults) -> str:
    """Rewrite the source bz2's [scenario] / [side] / [multiplayer]
    blocks so Wesnoth's playback uses the same PvP settings the sim
    used for its decisions. If we don't do this, the sim's view of
    income / starting gold / experience differs from Wesnoth's view,
    and the policy's recruit decisions (gated on gold) emit moves
    that Wesnoth's playback then rejects (insufficient gold) -- OOS.

    Updates in place via regex (whitespace-insensitive WML doesn't
    care about exact formatting):
      - top-level `mp_use_map_settings="yes"` (force "use map
        settings" semantics so [scenario]'s embedded values dominate
        any host-customized mp_* values).
      - top-level `mp_village_gold`, `mp_village_support`.
      - [scenario] `experience_modifier`.
      - each [side] gold / income (income is a side-level offset
        added to game_config::base_income=2; we set income=0 so the
        effective base income equals the default 2).
      - each [side] village_gold, village_support (per-side overrides
        that some replays set).
    """
    def repl_attr(name: str, value, content: str, flags=re.MULTILINE) -> str:
        # Replace `name=...` line with `name="value"`. If absent, leave
        # alone (Wesnoth will use its own default which matches our
        # defaults for the standard ladder cases).
        return re.sub(
            rf'^(\s*){re.escape(name)}=\"?[^\"\n]*\"?',
            rf'\1{name}="{value}"',
            content,
            flags=flags,
        )

    text = repl_attr("mp_use_map_settings", "yes", text)
    text = repl_attr("mp_village_gold",     defaults.village_gold, text)
    text = repl_attr("mp_village_support",  defaults.village_support, text)
    text = repl_attr("experience_modifier", defaults.experience_modifier, text)

    # Per-side rewrite: walk each [side]...[/side] block and rewrite
    # its gold / income / village_gold / village_support attrs.
    def rewrite_side(m: "re.Match") -> str:
        block = m.group(0)
        block = repl_attr("gold",            defaults.starting_gold, block)
        block = repl_attr("income",          0, block)  # offset; effective = 2
        block = repl_attr("village_gold",    defaults.village_gold, block)
        block = repl_attr("village_support", defaults.village_support, block)
        return block
    text = re.sub(
        r'\[side\][\s\S]*?\[/side\]',
        rewrite_side,
        text,
    )
    return text


def export_replay(
    sim:        WesnothSim,
    source_bz2: Path,
    out_path:   Path,
    *,
    pvp_defaults: Optional[PvPDefaults] = None,
) -> None:
    """Write `out_path` (a .bz2) such that Wesnoth can load it as a
    replay reproducing `sim`'s game from its initial state.

    `source_bz2` MUST be the same replay the sim was initialized from
    (via `WesnothSim.from_replay(<json.gz>)`). The .bz2 carries the
    full scenario WML the sim's initial state was derived from --
    map, sides, factions, leader stats. We can't reconstruct that
    from the sim's GameState alone (we'd lose modifications, era
    config, ai settings, mp_era_name, etc.).

    `pvp_defaults`: when provided, rewrite the source's
    economy/experience settings to match self-play "use map settings"
    behavior. Pass the SAME `PvPDefaults` you passed to
    `WesnothSim.from_replay` so sim and Wesnoth playback agree.
    """
    source_bz2 = Path(source_bz2)
    out_path = Path(out_path)
    log.info(f"loading source replay {source_bz2}")
    with bz2.open(source_bz2, "rt", encoding="utf-8", errors="ignore") as f:
        text = f.read()

    span = _find_final_replay_block(text)
    if span is None:
        raise RuntimeError(
            f"{source_bz2}: could not locate final [replay] block. "
            "File doesn't look like a Wesnoth replay.")
    start, end = span

    # Force oos_debug="no" in the top-level header. When the source
    # replay was saved with oos_debug="yes" (the host had "Strict
    # synchronization" enabled in the lobby), Wesnoth replaces every
    # synced command's checkup with `mp_debug_checkup`, which calls
    # `get_user_choice` against our (non-existent) `[checkup]` blocks
    # and immediately fires "expecting a user choice" on the very
    # first command -- even on a hand-built minimal trace with no
    # recruits or moves. Our exports don't emit `[checkup]` blocks,
    # so they're incompatible with debug-mode strictness; downgrading
    # to standard mode is safe and lossless for our use case.
    text = re.sub(
        r'^oos_debug=\"yes\"',
        'oos_debug="no"',
        text,
        count=1,
        flags=re.MULTILINE,
    )
    if pvp_defaults is not None:
        text = _rewrite_pvp_settings(text, pvp_defaults)
    span = _find_final_replay_block(text)  # re-locate after edits
    start, end = span

    new_replay = _build_replay_wml(sim.command_history)
    spliced = text[:start] + new_replay + text[end:]

    log.info(f"writing {out_path} ({len(sim.command_history)} commands)")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with bz2.open(out_path, "wt", encoding="utf-8") as f:
        f.write(spliced)


# ---------------------------------------------------------------------
# Source mapping (json.gz <-> .bz2)
# ---------------------------------------------------------------------

def find_source_bz2(json_gz_path: Path,
                    replays_raw: Path = Path("replays_raw")) -> Optional[Path]:
    """Given the path of a `replays_dataset/<id>.json.gz`, find the
    corresponding `replays_raw/<date>/<game_id>.bz2`. Returns None
    if not found (e.g., the user reorganized replays_raw)."""
    import gzip, json
    with gzip.open(json_gz_path, "rt", encoding="utf-8") as f:
        data = json.load(f)
    game_id = data.get("game_id", "")
    if not game_id:
        return None
    # game_id has double-underscore separating prefix from rest, but
    # the .bz2 filename uses the same convention. Try the literal
    # game_id first (matches recent dumps), then the legacy `_-_`
    # variant.
    candidates = [game_id + ".bz2",
                  game_id.replace("__", "_-_", 1) + ".bz2"]
    replays_raw = Path(replays_raw)
    if not replays_raw.exists():
        return None
    for date_dir in sorted(replays_raw.iterdir()):
        if not date_dir.is_dir():
            continue
        for cand in candidates:
            p = date_dir / cand
            if p.exists():
                return p
    return None


# ---------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------

def _cli(argv: List[str]) -> int:
    """`python tools/sim_to_replay.py REPLAY.json.gz OUT.bz2`
    runs a sim from REPLAY's initial state with the dummy policy and
    writes a Wesnoth-loadable replay to OUT.bz2."""
    import argparse
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    ap = argparse.ArgumentParser()
    ap.add_argument("source_json_gz", type=Path,
                    help="replays_dataset/<id>.json.gz to take init from")
    ap.add_argument("out_bz2", type=Path,
                    help="output .bz2 -- e.g., my_sim_run.bz2")
    ap.add_argument("--max-turns", type=int, default=40)
    ap.add_argument("--source-bz2", type=Path, default=None,
                    help="override automatic source-bz2 lookup")
    args = ap.parse_args(argv[1:])

    src_bz2 = args.source_bz2 or find_source_bz2(args.source_json_gz)
    if src_bz2 is None:
        log.error(
            f"could not auto-locate the .bz2 matching "
            f"{args.source_json_gz}. Pass --source-bz2 to override.")
        return 2
    log.info(f"using source bz2: {src_bz2}")

    from dummy_policy import DummyPolicy
    sim = WesnothSim.from_replay(args.source_json_gz, max_turns=args.max_turns)
    res = sim.run_game(DummyPolicy(), DummyPolicy())
    log.info(f"sim done: winner={res.winner} turns={res.turns} "
             f"ended_by={res.ended_by} "
             f"actions s1/s2 = {res.side1_actions}/{res.side2_actions}")

    export_replay(sim, source_bz2=src_bz2, out_path=args.out_bz2)
    log.info(f"wrote {args.out_bz2}")
    return 0


if __name__ == "__main__":
    sys.exit(_cli(sys.argv))
