"""Export a simulated game as a Wesnoth-loadable replay (.bz2).

Why: lets the user inspect simulated games directly in Wesnoth's GUI
to validate that the simulator's behavior matches Wesnoth's. Open the
exported file via Wesnoth's main menu -> Load Game -> Replays.

Strategy: a replay file is bz2-compressed WML. After
`[/scenario]` Wesnoth has a `[multiplayer]` block, optional
`[modification]`s, then a final `[replay]` block holding the command
stream. We take a SOURCE replay's bz2 (used as the scenario template,
since the simulator's initial state was built from it), strip the
final `[replay]`, and append our own command stream from the
simulator's `command_history`.

Caveats / known compromises:
- We don't emit `[checkup]` blocks (Wesnoth uses these to detect OOS
  on rejoin; absent on local replay playback Wesnoth will compute
  results from scratch).
- We DO emit `[random_seed]` dependent commands after each recruit /
  attack -- Wesnoth's replay engine requires them ("found [recruit]
  command in replay expecting a user choice" if missing). The seed
  itself is just an 8-hex-char value generated by the exporter; on
  playback Wesnoth uses it to roll traits / damage. Different seeds
  than the sim used internally, so per-strike hit/miss / trait rolls
  on playback will differ from the sim. Unit positions, turn
  structure, and which actions happened remain correct.
- Recruit/recall must include a `[from]` block with the leader's
  keep position; the sim records this at recruit time so the
  exporter doesn't have to reconstruct game state.
- We assume coords in `command_history` are 0-indexed (the sim's
  internal convention -- see replay_dataset.parse_map_data); the
  exporter adds 1 when emitting WML.

CLI usage:
    python tools/sim_to_replay.py SOURCE.bz2 OUT.bz2
    -- self-play one game from SOURCE's initial state (DummyPolicy)
       and write the export to OUT.

Library usage:
    from wesnoth_sim import WesnothSim
    from sim_to_replay import export_replay
    sim = WesnothSim.from_replay("foo.json.gz")
    sim.run_game(p1, p2)
    export_replay(sim, source_bz2="replays_raw/.../foo.bz2",
                  out_path="my_sim.bz2")
"""

from __future__ import annotations

import bz2
import logging
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# Make project root importable when run as a script.
_THIS = Path(__file__).resolve()
sys.path.insert(0, str(_THIS.parent.parent))
sys.path.insert(0, str(_THIS.parent))

from wesnoth_sim import PvPDefaults, RecordedCommand, WesnothSim, request_seed


log = logging.getLogger("sim_to_replay")


def _wml_quote(s: str) -> str:
    """Quote `s` for inclusion in a WML attribute value
    (`key="..."`).

    WML's parser treats backslashes as line-continuations and
    interprets `""` inside a quoted string as an embedded `"`. Other
    characters are literal. So:
      - `\\` must be doubled to `\\\\` (becomes a literal backslash).
      - `"` must be doubled to `""` (escapes the quote).
      - everything else passes through.

    Default-era unit names contain no special chars (verified by
    grepping `data/core/units/**/*.cfg` for `id=...` -- all match
    `[A-Za-z _:'-]+`), so this is dormant insurance for custom
    eras / scenarios. Without it, a unit type named e.g.
    `Custom"Unit` would produce malformed WML that Wesnoth can't
    parse; with it, the same name round-trips cleanly.
    """
    return s.replace("\\", "\\\\").replace('"', '""')


# ---------------------------------------------------------------------
# WML command emission
# ---------------------------------------------------------------------

def _wml_for_command(rc: RecordedCommand,
                     next_side: Optional[int] = None) -> str:
    """Render one RecordedCommand as a `[command]...[/command]` WML
    block. Coordinates are converted from the sim's 0-indexed
    convention to Wesnoth's 1-indexed WML by adding 1.

    `next_side` is required for end_turn (the side whose init_side
    comes next); it's derived from the history by `_build_replay_wml`.
    """
    if rc.kind == "init_side":
        side_n = rc.cmd[1]
        return (
            "\t[command]\n"
            "\t\t[init_side]\n"
            f"\t\t\tside_number={side_n}\n"
            "\t\t[/init_side]\n"
            "\t[/command]\n"
        )

    if rc.kind == "end_turn":
        # CRITICAL: emit `next_player_number = side + 1`, NOT a
        # modulo'd value. Wesnoth's `skip_empty_sides` decides
        # "is this a new turn?" by checking whether the requested
        # side index changes after modulo wrap-around. If we
        # already wrap (e.g., emit "1" after side 2 in 2p), Wesnoth
        # sees `1 == 1` post-modulo and concludes it's the SAME
        # turn -- so `next_turn()` never fires, `turn_` stays at 1
        # forever, and per-side MP never resets on init_side
        # (the `if (turn() > 1)` check in do_init_side fails).
        # That makes turn 2's first leader move corrupt because
        # the unit still has its leftover MP from turn 1.
        # Real replays emit "3" after side 2's end_turn in 2p; we
        # mirror that pattern here. Caller can override via
        # `next_side` if it has explicit history info, but the
        # default (side+1) is what Wesnoth expects.
        nxt = next_side if next_side is not None else rc.side + 1
        return (
            "\t[command]\n"
            "\t\t[end_turn]\n"
            f"\t\t\tnext_player_number={nxt}\n"
            "\t\t[/end_turn]\n"
            "\t[/command]\n"
        )

    if rc.kind == "move":
        # cmd = ["move", [sx, tx], [sy, ty], from_side]
        xs, ys = rc.cmd[1], rc.cmd[2]
        # Convert to 1-indexed.
        xs1 = ",".join(str(v + 1) for v in xs)
        ys1 = ",".join(str(v + 1) for v in ys)
        return (
            "\t[command]\n"
            f"\t\tfrom_side={rc.side}\n"
            "\t\t[move]\n"
            f"\t\t\tx=\"{xs1}\"\n"
            f"\t\t\ty=\"{ys1}\"\n"
            "\t\t[/move]\n"
            "\t[/command]\n"
        )

    if rc.kind == "attack":
        # cmd = ["attack", ax, ay, dx, dy, a_weapon, d_weapon, seed_hex]
        ax, ay, dx, dy = rc.cmd[1], rc.cmd[2], rc.cmd[3], rc.cmd[4]
        weapon = rc.cmd[5]
        d_weapon = rc.cmd[6] if len(rc.cmd) > 6 else -1
        return (
            "\t[command]\n"
            f"\t\tfrom_side={rc.side}\n"
            "\t\t[attack]\n"
            f"\t\t\tweapon={weapon}\n"
            f"\t\t\tdefender_weapon={d_weapon}\n"
            "\t\t\t[source]\n"
            f"\t\t\t\tx={ax + 1}\n"
            f"\t\t\t\ty={ay + 1}\n"
            "\t\t\t[/source]\n"
            "\t\t\t[destination]\n"
            f"\t\t\t\tx={dx + 1}\n"
            f"\t\t\t\ty={dy + 1}\n"
            "\t\t\t[/destination]\n"
            "\t\t[/attack]\n"
            "\t[/command]\n"
        )

    if rc.kind == "recruit":
        # cmd = ["recruit", unit_type, tx, ty, trait_seed]
        unit_type = _wml_quote(str(rc.cmd[1]))
        tx, ty = rc.cmd[2], rc.cmd[3]
        leader_pos = rc.extras.get("leader_pos", (tx, ty))
        lx, ly = leader_pos
        return (
            "\t[command]\n"
            f"\t\tfrom_side={rc.side}\n"
            "\t\t[recruit]\n"
            f"\t\t\ttype=\"{unit_type}\"\n"
            f"\t\t\tx={tx + 1}\n"
            f"\t\t\ty={ty + 1}\n"
            "\t\t\t[from]\n"
            f"\t\t\t\tx={lx + 1}\n"
            f"\t\t\t\ty={ly + 1}\n"
            "\t\t\t[/from]\n"
            "\t\t[/recruit]\n"
            "\t[/command]\n"
        )

    if rc.kind == "recall":
        # cmd = ["recall", unit_id, tx, ty]
        unit_id = _wml_quote(str(rc.cmd[1]))
        tx, ty = rc.cmd[2], rc.cmd[3]
        leader_pos = rc.extras.get("leader_pos", (tx, ty))
        lx, ly = leader_pos
        return (
            "\t[command]\n"
            f"\t\tfrom_side={rc.side}\n"
            "\t\t[recall]\n"
            f"\t\t\tvalue=\"{unit_id}\"\n"
            f"\t\t\tx={tx + 1}\n"
            f"\t\t\ty={ty + 1}\n"
            "\t\t\t[from]\n"
            f"\t\t\t\tx={lx + 1}\n"
            f"\t\t\t\ty={ly + 1}\n"
            "\t\t\t[/from]\n"
            "\t\t[/recall]\n"
            "\t[/command]\n"
        )

    log.warning(f"sim_to_replay: skipping unknown command kind: {rc.kind!r}")
    return ""


def _seed_from_recorded(rc: RecordedCommand) -> str:
    """Pull the seed the sim already used for this command. We assume
    the sim populated it via wesnoth_sim.request_seed(N) -- making
    the replay's [random_seed] match what the sim used internally,
    so trait/damage rolls agree bit-exact between sim and Wesnoth."""
    if rc.kind == "recruit":
        # cmd = ["recruit", unit_type, tx, ty, seed]
        return rc.cmd[4] if len(rc.cmd) > 4 and rc.cmd[4] else "00000000"
    if rc.kind == "attack":
        # cmd = ["attack", ax, ay, dx, dy, a_w, d_w, seed]
        return rc.cmd[7] if len(rc.cmd) > 7 and rc.cmd[7] else "00000000"
    return "00000000"


# ---------------------------------------------------------------------
# RNG-consumption gating
# ---------------------------------------------------------------------
# Wesnoth's synced_rng is LAZY: the seed from `[random_seed]` is only
# fetched on the FIRST `get_next_random()` call inside a synced
# command (see wesnoth_src/src/random_synced.cpp:31-49). If a recruit
# never calls RNG -- e.g. Skeleton (musthave=['undead'], num_traits=1,
# pool_size=0, single-gender) -- the seed is never fetched. Our
# `[random_seed]` follow-up is then orphaned: the outer replay loop
# sees a `dependent="yes"` command while is_unsynced=true and fires
# "found dependent command in replay while is_synced=false".
#
# So we have to predict whether each synced command consumes RNG and
# only emit `[random_seed]` for those that do. Real Wesnoth replays
# do this implicitly because the seed-write only happens when the
# server actually generated a seed.

_RNG_INFO_CACHE: Dict[str, dict] = {}


def _unit_trait_info(unit_type: str) -> dict:
    """Return the trait/gender info we need to predict synced RNG
    consumption for a recruit. Returns {} on lookup failure."""
    if unit_type in _RNG_INFO_CACHE:
        return _RNG_INFO_CACHE[unit_type]
    try:
        import json
        path = Path(__file__).resolve().parent.parent / "unit_stats.json"
        with path.open(encoding="utf-8") as f:
            data = json.load(f)
        u = data.get("units", {}).get(unit_type, {})
        t = u.get("traits", {}) or {}
        info = {
            "n_genders":  int(u.get("n_genders", 1)),
            "num_traits": int(t.get("num_traits", 2)),
            "musthave":   list(t.get("musthave", [])),
            "pool":       list(t.get("pool", [])),
        }
        _RNG_INFO_CACHE[unit_type] = info
        return info
    except Exception:
        _RNG_INFO_CACHE[unit_type] = {}
        return {}


def _recruit_consumes_synced_rng(unit_type: str) -> bool:
    """True iff Wesnoth's recruit handler calls `get_random_int` for
    this unit type, which is the trigger for `synced_rng::initialize`
    fetching the [random_seed] payload.

    Wesnoth's order in `unit::init` (wesnoth_src/src/units/unit.cpp:714):
      1. generate_gender -- one synced RNG call iff genders.size() > 1
         (single-gender unit_types like Skeleton short-circuit and
         consume zero).
      2. facing_ -- uses default_instance() (NON-synced); doesn't
         touch our seed.
      3. advance_to -> generate_traits -- per missing trait beyond
         musthaves, one synced call to pick from the available pool.
         If musthaves already fill num_traits OR the pool is empty
         after filtering, the for-loop never enters.
    """
    info = _unit_trait_info(unit_type)
    if not info:
        # Unknown unit type -- be conservative and emit the seed.
        # Worst case Wesnoth ignores it; missing seed produces the
        # actual OOS we're trying to fix.
        return True
    if info["n_genders"] > 1:
        return True
    n_random = max(0, info["num_traits"] - len(info["musthave"]))
    if n_random <= 0:
        return False
    # If pool minus already-applied musthaves is empty, the loop
    # exits via the `if(candidate_traits.empty()) break` branch
    # without calling RNG.
    available = [t for t in info["pool"] if t not in info["musthave"]]
    return len(available) > 0


def _command_consumes_synced_rng(rc: RecordedCommand) -> bool:
    """Whether a recorded command's Wesnoth-side execution calls
    synced RNG (and thus should receive a [random_seed] follow-up).
    Recruit: depends on unit type (see _recruit_consumes_synced_rng).
    Attack: always (combat rolls every strike's hit/miss).
    Other kinds: never (caller doesn't reach here)."""
    if rc.kind == "recruit":
        unit_type = rc.cmd[1] if len(rc.cmd) > 1 else ""
        return _recruit_consumes_synced_rng(unit_type)
    if rc.kind == "attack":
        return True
    return False


def _wml_choose_command(side: int, value: int) -> str:
    """Emit a synthetic `[command] dependent="yes" [choose]` block --
    Wesnoth's record of an advancement choice. After every attack that
    levels up the attacker and/or defender, `attack_unit_and_advance`
    (wesnoth_src/src/actions/attack.cpp:1556-1573) calls
    `advance_unit_at` per advancing unit, which goes through
    `mp_sync::get_user_choice("choose", ...)`. The replay records the
    chosen advancement index here. Without these, replay playback
    errors with "expecting a user choice" the first time a unit levels
    up mid-battle.

    Order in the WML stream MUST be: attack [command], its
    [random_seed] follow-up, then attacker's [choose] (if attacker
    advanced), then defender's [choose] (if defender advanced).

    Format mirrors a real-replay sample (`from_side` is the unit's
    OWNER side, not "server" -- different from [random_seed] which is
    server-emitted)."""
    return (
        "[command]\n"
        "dependent=\"yes\"\n"
        f"from_side=\"{side}\"\n"
        "[choose]\n"
        f"value=\"{value}\"\n"
        "[/choose]\n"
        "[/command]\n"
    )


def _wml_random_seed_command(seed: str, request_id: int) -> str:
    """Emit a synthetic `[command] ... [random_seed]` block. Wesnoth's
    replay engine demands one of these after every command that needs
    a random roll (recruit -> trait roll, attack -> damage rolls);
    without them you get 'expecting a user choice' on playback. The
    seed must be the SAME hex value the sim used internally so both
    sides agree on traits / damage.

    Indentation: emitted unindented to match the formatting Wesnoth
    itself produces for dependent commands. WML's parser is supposed
    to be whitespace-insensitive, but matching the real-replay style
    is one less variable when debugging OOS issues."""
    return (
        "[command]\n"
        "dependent=\"yes\"\n"
        "from_side=\"server\"\n"
        "[random_seed]\n"
        f"new_seed=\"{seed}\"\n"
        f"request_id=\"{request_id}\"\n"
        "[/random_seed]\n"
        "[/command]\n"
    )


# Commands that need a [random_seed] follow-up. Verified for recruit
# (trait roll) and attack (damage roll) by inspecting real Wesnoth
# replays. Recall does NOT need one -- recalled units' traits were
# already rolled at recruit time.
_NEEDS_RNG = frozenset({"recruit", "attack"})


def _build_replay_wml(history: List[RecordedCommand]) -> str:
    """Emit `[replay] ... [/replay]` content from a command history.
    After each random-rolling command we emit a synthetic
    `[random_seed]` follow-up so Wesnoth's replay engine has a 'user
    choice' to consume.

    end_turn's `next_player_number` is left unset here so the emitter
    falls back to `rc.side + 1` -- the convention Wesnoth's
    skip_empty_sides expects for detecting turn wrap-around. (Looking
    up the actual next init_side and using that value would emit "1"
    after side 2 in 2p, which Wesnoth treats as 'still on turn 1' --
    breaking turn 2's MP reset.)
    """
    parts: List[str] = []
    request_id = 0
    for rc in history:
        parts.append(_wml_for_command(rc, next_side=None))
        # Only emit [random_seed] for commands Wesnoth's synced_rng
        # will actually consume. Skeleton-class recruits with no
        # random traits never call get_next_random; emitting a
        # dangling [random_seed] for them produces "found dependent
        # command in replay while is_synced=false" on the NEXT
        # outer-loop iteration.
        if rc.kind in _NEEDS_RNG and _command_consumes_synced_rng(rc):
            request_id += 1
            seed = _seed_from_recorded(rc)
            parts.append(_wml_random_seed_command(seed, request_id))
        # Advancement [choose] follow-ups: emitted AFTER the attack's
        # [random_seed] so the order matches Wesnoth's
        # `attack_unit_and_advance` path (attack -> RNG follow-up ->
        # advancer per side, attacker first then defender). Sim's
        # `_maybe_advance_unit` always picks targets[0], so value=0.
        if rc.kind == "attack":
            for side, idx in rc.extras.get("advance_choices", []):
                parts.append(_wml_choose_command(side, idx))
    return "[replay]\n" + "".join(parts) + "[/replay]\n"


# ---------------------------------------------------------------------
# Source-file splicing
# ---------------------------------------------------------------------

def _find_final_replay_block(text: str) -> Optional[tuple]:
    """Locate the offsets of the final `[replay]...[/replay]` block in
    a decompressed replay file. Returns (start, end) where start is
    the offset of the `[replay]` line and end is just past `[/replay]`.

    The file may have an empty initial `[replay]` block (with just
    `[upload_log]`) before `[scenario]`; we always want the LAST one
    in the file, after `[/scenario]`.

    Robustness: WML tags like `[replay]` / `[/replay]` always appear
    at the start of a line in real replay files, but the previous
    plain `text.rfind("[replay]")` would also match a literal
    `[replay]` substring inside a quoted attribute value (e.g. a
    `[message] description="..."` body that happened to mention the
    string). Anchor to start-of-line via regex so quoted-string
    occurrences don't mislead the splice.
    """
    import re
    open_re  = re.compile(r"^\[replay\]\s*$",  re.MULTILINE)
    close_re = re.compile(r"^\[/replay\]\s*$", re.MULTILINE)
    open_matches = list(open_re.finditer(text))
    if not open_matches:
        return None
    last_open_match = open_matches[-1]
    close_match = close_re.search(text, last_open_match.end())
    if close_match is None:
        return None
    return (last_open_match.start(), close_match.end())


def _rewrite_sides_for_sim(text: str, sim: "WesnothSim") -> str:
    """Rewrite each `[side]...[/side]` so the SOURCE bz2's faction /
    leader / recruit list match the SIM's actual setup.

    Why this matters (the bug the BACKLOG flagged 2026-04-30):
    `sim_to_replay` splices our `[replay]` block into a source `.bz2`
    template. After the 2026-04-30 scenario-pool pivot, sim factions
    are randomized at game start — they no longer match whatever
    factions the source replay happened to have. Without this
    rewrite, Wesnoth's playback instantiates the SOURCE's leaders
    (e.g. Red Mage / Deathblade for Arcanclave) and every recruit
    in our `[replay]` then mismatches (Drake Burner from a side
    Wesnoth thinks recruits human-Loyalist units, etc.).

    Per-side rewrites:
      - top-level `type="<leader unit type>"` (the type attr on
        `[side]` itself, distinct from the `[unit]`-level type)
      - `faction="<faction name>"` and `faction_name="<same>"`
      - `recruit="<comma-joined list>"`
      - the leader `[unit]` sub-block (we identify it via
        `canrecruit=yes` and replace its contents with a minimal
        block that lets Wesnoth re-roll the leader from scratch at
        the keep position). Other `[unit]` blocks inside the side
        (scenario-pre-placed scenery / petrified units / etc.) are
        preserved.

    Keep position: stolen from the original leader `[unit]`'s `x=`
    / `y=` so we don't move the leader. The 2p_*.cfg [side] keep
    positions are fixed per scenario, so this is invariant.
    """
    # Build per-side info from the sim. Leader position comes from
    # the live game state -- if the sim has already started, the
    # leader may have moved, but for replay export we want the
    # INITIAL keep position. Fall back to the live position; for
    # demo exports the sim is run from a fresh state anyway.
    side_leader: dict = {}
    for u in sim.gs.map.units:
        if u.is_leader:
            side_leader[u.side] = (u.name, u.position.x, u.position.y)
    side_meta: dict = {}
    for i, s in enumerate(sim.gs.sides, start=1):
        # SideInfo is a flat dataclass; the list position is the
        # side number (1-indexed in WML, 1-indexed here for parity).
        side_num = getattr(s, "side_num", i)
        side_meta[side_num] = {
            "faction": s.faction or "",
            "recruit": ",".join(s.recruits or []),
        }

    if not side_leader:
        # Nothing to rewrite (sim has no leaders -- pathological).
        return text

    def rewrite_one_side(m: "re.Match") -> str:
        block = m.group(0)
        # Wesnoth replays inconsistently quote attrs -- the
        # `side="1"` form (with quotes) appears in saves that went
        # through Wesnoth's save/load cycle, while `side=1` (unquoted)
        # appears in hand-built configs and some scenarios. Accept
        # both forms; otherwise the rewrite would silently no-op on
        # quoted sources.
        side_m = re.search(
            r'^\s*side=\"?(\d+)\"?\s*$', block, re.MULTILINE)
        if side_m is None:
            return block
        side_num = int(side_m.group(1))
        leader = side_leader.get(side_num)
        if leader is None:
            return block
        leader_type, _, _ = leader
        meta = side_meta.get(side_num, {"faction": "", "recruit": ""})

        # Top-level [side] attrs. `type=` is on the [side] tag itself
        # (Wesnoth uses it to populate the leader when no [unit] is
        # provided); always overwrite.
        block = re.sub(
            r'^(\s*)type=\"?[^\"\n]*\"?',
            rf'\1type="{leader_type}"',
            block, count=1, flags=re.MULTILINE,
        )
        if meta["faction"]:
            block = re.sub(
                r'^(\s*)faction=\"?[^\"\n]*\"?',
                rf'\1faction="{meta["faction"]}"',
                block, count=1, flags=re.MULTILINE,
            )
            block = re.sub(
                r'^(\s*)faction_name=\"?[^\"\n]*\"?',
                rf'\1faction_name="{meta["faction"]}"',
                block, count=1, flags=re.MULTILINE,
            )
        if meta["recruit"]:
            block = re.sub(
                r'^(\s*)recruit=\"?[^\"\n]*\"?',
                rf'\1recruit="{meta["recruit"]}"',
                block, count=1, flags=re.MULTILINE,
            )

        # Locate the leader [unit] block (identified by canrecruit=yes
        # somewhere in its body). Replace its body with a minimal
        # leader stub at the source's keep position; scenario-placed
        # NON-leader units stay untouched.
        unit_re = re.compile(r'\[unit\][\s\S]*?\[/unit\]')
        def maybe_rewrite_unit(um: "re.Match") -> str:
            ubody = um.group(0)
            if 'canrecruit=yes' not in ubody and 'canrecruit="yes"' not in ubody:
                return ubody  # not the leader
            # Pull x/y from the original block -- it's the keep
            # position, scenario-invariant per side.
            x_m = re.search(r'^\s*x=\"?(\d+)\"?', ubody, re.MULTILINE)
            y_m = re.search(r'^\s*y=\"?(\d+)\"?', ubody, re.MULTILINE)
            if not x_m or not y_m:
                return ubody  # unparseable; leave it
            kx, ky = x_m.group(1), y_m.group(1)
            # Build a minimal leader [unit] block. Wesnoth will roll
            # traits + HP + attacks from the unit_type definition at
            # game start. `random_traits=yes` lets the trait gen run
            # via the synced RNG (matching the seeds in our [replay]
            # block).
            return (
                "[unit]\n"
                f'    type="{leader_type}"\n'
                f"    side={side_num}\n"
                f"    x={kx}\n"
                f"    y={ky}\n"
                "    canrecruit=yes\n"
                "    random_traits=yes\n"
                "[/unit]"
            )
        block = unit_re.sub(maybe_rewrite_unit, block)
        return block

    return re.sub(r'\[side\][\s\S]*?\[/side\]', rewrite_one_side, text)


def _rewrite_pvp_settings(text: str, defaults: PvPDefaults) -> str:
    """Rewrite the source bz2's [scenario] / [side] / [multiplayer]
    blocks so Wesnoth's playback uses the same PvP settings the sim
    used for its decisions. If we don't do this, the sim's view of
    income / starting gold / experience differs from Wesnoth's view,
    and the policy's recruit decisions (gated on gold) emit moves
    that Wesnoth's playback then rejects (insufficient gold) -- OOS.

    Updates in place via regex (whitespace-insensitive WML doesn't
    care about exact formatting):
      - top-level `mp_use_map_settings="yes"` (force "use map
        settings" semantics so [scenario]'s embedded values dominate
        any host-customized mp_* values).
      - top-level `mp_village_gold`, `mp_village_support`.
      - [scenario] `experience_modifier`.
      - each [side] gold / income (income is a side-level offset
        added to game_config::base_income=2; we set income=0 so the
        effective base income equals the default 2).
      - each [side] village_gold, village_support (per-side overrides
        that some replays set).
    """
    def repl_attr(name: str, value, content: str, flags=re.MULTILINE) -> str:
        # Replace `name=...` line with `name="value"`. If absent, leave
        # alone (Wesnoth will use its own default which matches our
        # defaults for the standard ladder cases).
        return re.sub(
            rf'^(\s*){re.escape(name)}=\"?[^\"\n]*\"?',
            rf'\1{name}="{value}"',
            content,
            flags=flags,
        )

    text = repl_attr("mp_use_map_settings", "yes", text)
    text = repl_attr("mp_village_gold",     defaults.village_gold, text)
    text = repl_attr("mp_village_support",  defaults.village_support, text)
    text = repl_attr("experience_modifier", defaults.experience_modifier, text)

    # Per-side rewrite: walk each [side]...[/side] block and rewrite
    # its gold / income / village_gold / village_support attrs.
    def rewrite_side(m: "re.Match") -> str:
        block = m.group(0)
        block = repl_attr("gold",            defaults.starting_gold, block)
        block = repl_attr("income",          0, block)  # offset; effective = 2
        block = repl_attr("village_gold",    defaults.village_gold, block)
        block = repl_attr("village_support", defaults.village_support, block)
        return block
    text = re.sub(
        r'\[side\][\s\S]*?\[/side\]',
        rewrite_side,
        text,
    )
    return text


# ---------------------------------------------------------------------
# From-scratch save composition
# ---------------------------------------------------------------------
#
# Goal: emit a Wesnoth-loadable .bz2 from `sim` + scenario_id ALONE,
# without splicing onto any `replays_raw/*.bz2`. The output is byte-for-
# byte compatible with what Wesnoth's "Multiplayer -> Create Game" path
# produces: top-level scalars + empty initial [replay] + [scenario]
# (with full map_data + sides + ToD + music) + [carryover_sides_start]
# + [multiplayer] + [statistics] + [era] (default-era expansion) +
# [replay] (our commands).
#
# Strategy: most of the boilerplate (era expansion, ToD schedule, music
# playlist, prestart trait macros, top-level scalars) is identical
# across all 2p default-era scenarios. We carry it as a one-shot
# template under `tools/templates/`, extracted once from a known-good
# strict-sync Wesnoth save. Per-scenario emission swaps in:
#   - scenario_id + description + display name (from the .cfg)
#   - map_data (inlined from the referenced .map file)
#   - [side] blocks rendered from sim state
#   - [replay] block from sim.command_history
#
# This removes the dependency on `replays_raw/`: as long as the
# wesnoth_src checkout has the scenario .cfg + .map, we can export.

_TEMPLATES_DIR = Path(__file__).resolve().parent / "templates"
_SCAFFOLD_PATH = _TEMPLATES_DIR / "wesnoth_save_scaffold.wml"
_SCENARIO_TAIL_PATH = _TEMPLATES_DIR / "wesnoth_scenario_tail.wml"
_WESNOTH_SRC = Path(__file__).resolve().parent.parent / "wesnoth_src"
_SCENARIO_DIR = _WESNOTH_SRC / "data" / "multiplayer" / "scenarios"
_MAPS_DIR = _WESNOTH_SRC / "data" / "multiplayer" / "maps"


def _read_template(path: Path) -> str:
    """Read a `tools/templates/*.wml` file, dropping `^# ...` comment
    lines we added at extraction time (those would confuse Wesnoth's
    WML parser which uses `#` only for `#textdomain` / `#define`
    directives at line start). Wesnoth's actual comment marker is
    a leading `#` outside macro-definition context, but since we don't
    know the parser's tolerance, strip them defensively."""
    text = path.read_text(encoding="utf-8")
    out_lines = []
    for line in text.splitlines(keepends=True):
        # Drop our own annotation comments (lines starting with `# `).
        # Keep `#textdomain` directives -- those are real WML.
        if line.startswith("# "):
            continue
        out_lines.append(line)
    return "".join(out_lines)


_CFG_BY_SCENARIO_ID_CACHE: Dict[str, Path] = {}


def _scenario_cfg_path(scenario_id: str) -> Optional[Path]:
    """Find `wesnoth_src/data/multiplayer/scenarios/*.cfg` whose
    `[multiplayer] id=` matches `scenario_id`.

    The id-to-filename mapping is mostly mechanical (strip
    `multiplayer_` -> prepend `2p_`), but Wesnoth doesn't enforce it:
    Caves of the Basilisk's file is `2p_Caves_of_the_Basilisk.cfg`
    yet its scenario id is `multiplayer_Basilisk`. Case can also
    diverge (Elensefar Courtyard's id is lowercase, filename is
    CamelCase). The robust lookup is: parse each .cfg's top-level
    `id=`, match against `scenario_id` exactly. Cached after the
    first call.
    """
    if not scenario_id.startswith("multiplayer_"):
        return None
    if not _CFG_BY_SCENARIO_ID_CACHE:
        # Populate cache from every 2p_*.cfg.
        for cfg in _SCENARIO_DIR.glob("2p_*.cfg"):
            try:
                text = cfg.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            # First `id=multiplayer_*` wins (top-level [multiplayer]).
            m = re.search(
                r'^\s*id\s*=\s*"?(multiplayer_[A-Za-z0-9_]+)"?\s*$',
                text, re.MULTILINE,
            )
            if m:
                _CFG_BY_SCENARIO_ID_CACHE[m.group(1)] = cfg
    return _CFG_BY_SCENARIO_ID_CACHE.get(scenario_id)


def _scrape_scenario_metadata(cfg_path: Path) -> Dict[str, str]:
    """Read a `2p_*.cfg` and pull out the fields we need to emit:
    description, name, id, map_file. Wesnoth's WML attributes can use
    either `attr=value` or `attr="value"`; we accept both and strip
    quotes. Multi-line description strings (joined via `+` and
    enclosed in `_"..."`) collapse to the first quoted run, which
    is sufficient for our save's `description=` attr.
    """
    text = cfg_path.read_text(encoding="utf-8", errors="replace")
    out: Dict[str, str] = {}
    for key in ("id", "name", "description", "map_file"):
        # Wesnoth WML formats the relevant attrs in three shapes:
        #   key=value             (unquoted, e.g. id=multiplayer_Foo)
        #   key="value"           (quoted)
        #   key= _ "value"        (translatable; space + `_` before quote)
        # The third is most common for `name=` and `description=`.
        # Build a regex tolerant of all three.
        m = re.search(
            rf'^\s*{key}\s*=\s*_?\s*"([^"]*)"\s*$',
            text, re.MULTILINE,
        )
        if m is None:
            # Unquoted form.
            m = re.search(
                rf'^\s*{key}\s*=\s*([^"\n]+?)\s*$',
                text, re.MULTILINE,
            )
        if m:
            out[key] = m.group(1).strip()
    return out


def _load_map_data(map_file_attr: str) -> str:
    """Resolve a `map_file=multiplayer/maps/2p_<Name>.map` reference
    to the actual map contents (inlined into [scenario]'s map_data=).

    Wesnoth's `map_file=` is repo-relative to `wesnoth_src/data/`,
    so we resolve under there."""
    rel = map_file_attr.strip().strip('"').lstrip("/")
    # `multiplayer/maps/2p_*.map` -> `wesnoth_src/data/multiplayer/maps/...`
    abs_path = _WESNOTH_SRC / "data" / rel
    if not abs_path.exists():
        raise FileNotFoundError(
            f"map file not found at {abs_path} "
            f"(map_file attr was {map_file_attr!r})"
        )
    return abs_path.read_text(encoding="utf-8")


def _render_side_block(
    side_num:    int,
    leader_type: str,
    keep_x:      int,
    keep_y:      int,
    faction:     str,
    recruit:     List[str],
    gold:        int,
    village_gold: int,
    village_support: int,
    color:       str,
    team_name:   str,
    user_team_name: str,
    pre_placed_villages: List[Tuple[int, int]] = (),
) -> str:
    """Render one `[side]...[/side]` block. Mirrors what Wesnoth emits
    for a fresh-game save: a top-level type= for the leader (Wesnoth
    instantiates from the unit-type at game start) plus the side-
    level economy/faction/recruit attrs. A `random_traits=yes` flag
    on the leader unit ensures Wesnoth rolls traits via the synced
    RNG at scenario start, matching the seeds in our [replay]."""
    parts = ["[side]"]
    parts += [
        f'\tallow_changes="yes"',
        f'\tallow_player="yes"',
        f'\tcanrecruit="yes"',
        f'\tchose_random="no"',
        f'\tcolor="{color}"',
        f'\tcontroller="human"',
        f'\tcurrent_player="Sim Player {side_num}"',
        f'\tfaction="{faction}"',
        f'\tfaction_name="{faction}"',
        f'\tfog="no"',  # PvP default ladder has fog off
        f'\tgold="{gold}"',
        f'\tincome="0"',
        f'\tis_host="{"yes" if side_num == 1 else "no"}"',
        f'\tis_local="yes"',
        f'\tname="Sim Player {side_num}"',
        f'\tplayer_id="sim_player_{side_num}"',
        f'\trecruit="{",".join(recruit)}"',
        f'\tshroud="no"',
        f'\tside="{side_num}"',
        f'\tteam_name="{team_name}"',
        f'\ttype="{leader_type}"',
        f'\tuser_team_name="{user_team_name}"',
        f'\tvillage_gold="{village_gold}"',
        f'\tvillage_support="{village_support}"',
    ]
    # Pre-placed villages (some scenarios reserve hexes for sides).
    for vx, vy in pre_placed_villages:
        parts.append("\t[village]")
        parts.append(f"\t\tx={vx}")
        parts.append(f"\t\ty={vy}")
        parts.append("\t[/village]")
    # No explicit [unit] block: Wesnoth instantiates the leader from
    # the [side]'s `type=` attr at scenario start, placing it on the
    # map's `<N> K*` keep marker. Trait roll uses the synced RNG so
    # it'll match our [replay] commands as long as `random_traits=yes`
    # is the era default (which it is for default era). Matches the
    # shape Wesnoth itself writes in its initial save files (verified
    # against tests/fixtures/strict_sync_hamlets_t9.bz2).
    parts.append("[/side]")
    _ = (keep_x, keep_y)  # unused now -- kept in API for future use
    return "\n".join(parts) + "\n"


def _color_for_side(side_num: int) -> Tuple[str, str, str]:
    """Wesnoth's default side-color / team-name conventions.
    (color, team_name, user_team_name). Side 1 = red/north,
    side 2 = blue/south. Mirrors the in-tree 2p_*.cfg defaults
    (Hamlets uses north/south; others vary, but these names are
    cosmetic for replay playback)."""
    if side_num == 1:
        return ("red", "north", "wesnoth-multiplayerteamname^North")
    return ("blue", "south", "wesnoth-multiplayerteamname^South")


def _scrape_map_keep_positions(map_data: str) -> Dict[int, Tuple[int, int]]:
    """Find per-side starting keep positions in a map's terrain grid.
    Each tile may be prefixed with `<N> ` (e.g. `1 Kh`, `2 Kud`) to
    mark side N's starting keep. WML coords are 1-indexed.

    Returns side_num -> (x, y). Map's first row is y=1, first col is
    x=1. Tiles are comma-separated; rows are newline-separated.
    Missing side -> not in the map -> caller errors loudly.
    """
    out: Dict[int, Tuple[int, int]] = {}
    rows = [r for r in map_data.splitlines() if r.strip()]
    for y, row in enumerate(rows, start=1):
        tiles = [t.strip() for t in row.split(",")]
        for x, tile in enumerate(tiles, start=1):
            # Match "<N> <code>" prefix where <N> is the side number.
            m = re.match(r'^(\d+)\s+(.+)$', tile)
            if m:
                side = int(m.group(1))
                if side not in out:
                    out[side] = (x, y)
    return out


def _scrape_scenario_starting_gold(cfg_path: Path) -> Dict[int, int]:
    """Walk a `2p_*.cfg` for per-side `gold=N` attrs. Some scenarios
    (Arcanclave, Weldyn Channel) override the default 100 starting
    gold; we need the scenario-defined value to populate the save's
    `[side] gold=` attr correctly. Without it Wesnoth would show
    the wrong starting gold when the replay viewer renders turn 1.

    Returns side_num -> gold. Sides without an explicit `gold=`
    don't appear in the map; callers fall back to 100 (Wesnoth's
    default starting gold for `mp_use_map_settings=yes`).
    """
    text = cfg_path.read_text(encoding="utf-8", errors="replace")
    out: Dict[int, int] = {}
    side_re = re.compile(r'\[side\]([\s\S]*?)\[/side\]')
    for sm in side_re.finditer(text):
        body = sm.group(1)
        sn_m = re.search(r'^\s*side\s*=\s*(\d+)', body, re.MULTILINE)
        gd_m = re.search(r'^\s*gold\s*=\s*(\d+)', body, re.MULTILINE)
        if sn_m and gd_m:
            out[int(sn_m.group(1))] = int(gd_m.group(1))
    return out


def _scrape_scenario_villages(cfg_path: Path) -> Dict[int, List[Tuple[int, int]]]:
    """Walk a `2p_*.cfg` scenario file and pull out per-side pre-placed
    `[village] x=N y=N [/village]` entries. Used by Hamlets, Sablestone,
    Arcanclave, and a few others that grant a side a starting village
    via the .cfg [side] block.

    Returns side_num -> list of (x, y) WML coords (1-indexed).
    """
    text = cfg_path.read_text(encoding="utf-8", errors="replace")
    out: Dict[int, List[Tuple[int, int]]] = {1: [], 2: []}
    # Walk per-[side] block.
    side_re = re.compile(r'\[side\]([\s\S]*?)\[/side\]')
    village_re = re.compile(r'\[village\][\s\S]*?x\s*=\s*(\d+)[\s\S]*?y\s*=\s*(\d+)[\s\S]*?\[/village\]')
    for sm in side_re.finditer(text):
        body = sm.group(1)
        sn_m = re.search(r'^\s*side\s*=\s*(\d+)', body, re.MULTILINE)
        if not sn_m:
            continue
        sn = int(sn_m.group(1))
        if sn not in out:
            out[sn] = []
        for vm in village_re.finditer(body):
            out[sn].append((int(vm.group(1)), int(vm.group(2))))
    return out


def build_save_wml(
    sim:          WesnothSim,
    *,
    pvp_defaults: Optional[PvPDefaults] = None,
) -> str:
    """Compose a complete Wesnoth save WML string for the sim's game.

    Inputs: `sim.scenario_id` selects the scenario template (from
    wesnoth_src). `sim.gs` selects per-side leader / faction /
    recruit / starting gold. `sim.command_history` becomes the
    [replay] block.

    No source bz2 is read. The only external dependencies are:
      - tools/templates/wesnoth_save_scaffold.wml (extracted once)
      - tools/templates/wesnoth_scenario_tail.wml (extracted once)
      - wesnoth_src/data/multiplayer/scenarios/2p_<Name>.cfg
      - wesnoth_src/data/multiplayer/maps/2p_<Name>.map
    """
    scenario_id = sim.scenario_id
    cfg_path = _scenario_cfg_path(scenario_id)
    if cfg_path is None:
        raise RuntimeError(
            f"no wesnoth_src .cfg found for scenario_id={scenario_id!r}; "
            f"checked {_SCENARIO_DIR}"
        )

    scen_meta = _scrape_scenario_metadata(cfg_path)
    scen_name = scen_meta.get("name", scenario_id)
    scen_desc = scen_meta.get("description", "")
    map_file  = scen_meta.get("map_file", "")
    if not map_file:
        raise RuntimeError(
            f"{cfg_path.name}: no map_file= attr; cannot inline map_data"
        )
    map_data = _load_map_data(map_file)

    pvp = pvp_defaults or PvPDefaults()
    exp_mod        = pvp.experience_modifier
    village_gold   = pvp.village_gold
    village_support = pvp.village_support

    # Pre-placed villages per side (Hamlets, Sablestone, Arcanclave).
    village_map = _scrape_scenario_villages(cfg_path)
    # Per-side starting gold from the .cfg; falls back to PvP default
    # 100 when the scenario doesn't specify.
    cfg_gold = _scrape_scenario_starting_gold(cfg_path)
    # Per-side keep positions from the map (`1 Kh`, `2 Kud` markers).
    # Authoritative initial leader position regardless of sim state.
    keep_pos = _scrape_map_keep_positions(map_data)

    # ---- per-side blocks rendered from scenario + sim state ----
    # Leaders / factions / recruits / starting-gold reflect the sim's
    # INITIAL configuration. Wesnoth's playback engine plays the
    # [replay] forward from this initial state, so the [side] gold=
    # must be the starting gold (not the sim's current end-of-game
    # gold).
    side_blocks: List[str] = []
    leaders = {u.side: u for u in sim.gs.map.units if u.is_leader}
    for i, side_info in enumerate(sim.gs.sides, start=1):
        leader = leaders.get(i)
        if leader is None:
            raise RuntimeError(
                f"sim has no leader for side {i}; cannot emit [side]")
        # Keep position from the map (1-indexed WML coords). If the
        # map doesn't have a marker for this side, fall back to the
        # sim's leader position (0-indexed -> 1-indexed conversion).
        if i in keep_pos:
            keep_x, keep_y = keep_pos[i]
        else:
            keep_x = leader.position.x + 1
            keep_y = leader.position.y + 1
        # Starting gold: .cfg value if present, else PvP default.
        starting_gold = cfg_gold.get(i, pvp.starting_gold)
        color, team_name, user_team_name = _color_for_side(i)
        side_blocks.append(_render_side_block(
            side_num=i,
            leader_type=leader.name,
            keep_x=keep_x, keep_y=keep_y,
            faction=side_info.faction or "Custom",
            recruit=list(side_info.recruits or []),
            gold=starting_gold,
            village_gold=village_gold,
            village_support=village_support,
            color=color,
            team_name=team_name,
            user_team_name=user_team_name,
            pre_placed_villages=village_map.get(i, []),
        ))

    # ---- compose [scenario] block ----
    scenario_tail = _read_template(_SCENARIO_TAIL_PATH)
    scenario_block_parts = [
        "[scenario]",
        f'description="{_wml_quote(scen_desc)}"',
        f'experience_modifier="{exp_mod}"',
        'has_mod_events="yes"',
        f'id="{scenario_id}"',
        'loaded_resources=""',
        f'map_data="{map_data.rstrip()}\n"',
        f'map_file="{map_file}"',
        f'name="{_wml_quote(scen_name)}"',
        'objectives="<big>Victory:</big>\n<span color=\'#00ff00\'>• Defeat the enemy leader(s)</span>"',
        'random_start_time="no"',
        'turns="-1"',
        # Then the ToD schedule + music + prestart events tail.
        scenario_tail.rstrip(),
        # Then per-side blocks.
        *side_blocks,
        "[/scenario]",
    ]
    scenario_block = "\n".join(scenario_block_parts) + "\n"

    # ---- compose the rest from the scaffold ----
    scaffold = _read_template(_SCAFFOLD_PATH)
    # Substitute placeholders.
    import random
    rng_seed = f"{random.randint(0, 0xffffffff):08x}"
    label = f"Sim Replay - {scen_name}"
    scaffold = (scaffold
        .replace("%LABEL%", _wml_quote(label))
        .replace("%SCENARIO_ID%", scenario_id)
        .replace("%SCENARIO_NAME%", _wml_quote(scen_name))
        .replace("%EXP_MOD%", str(exp_mod))
        .replace("%VILLAGE_GOLD%", str(village_gold))
        .replace("%VILLAGE_SUPPORT%", str(village_support))
        .replace("%RANDOM_SEED%", rng_seed)
    )

    # The scaffold is ordered: prelude + empty [replay] + carryover +
    # multiplayer + statistics + era. We need to insert the [scenario]
    # block BETWEEN the empty [replay] and [carryover_sides_start].
    insert_after = scaffold.find("[/replay]") + len("[/replay]\n")
    save = (scaffold[:insert_after]
            + scenario_block
            + scaffold[insert_after:])

    # Append the actual replay commands at the end.
    replay_block = _build_replay_wml(sim.command_history)
    save = save.rstrip() + "\n" + replay_block
    return save


def export_replay_from_scratch(
    sim:      WesnothSim,
    out_path: Path,
    *,
    pvp_defaults: Optional[PvPDefaults] = None,
) -> None:
    """Compose a Wesnoth-loadable .bz2 from sim state + scenario_id
    alone (no `replays_raw/*.bz2` dependency). Writes the result to
    `out_path`. The output should be loadable via Wesnoth's
    File -> Load Game -> Replays panel.

    Use this instead of `export_replay` when you don't have a matching
    source .bz2 OR when the sim's factions/leaders/scenario differ
    from any source you'd otherwise splice onto.
    """
    save_wml = build_save_wml(sim, pvp_defaults=pvp_defaults)
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    log.info(
        f"writing {out_path} from scratch "
        f"({len(sim.command_history)} commands, "
        f"{len(save_wml)} chars of WML)"
    )
    with bz2.open(out_path, "wt", encoding="utf-8") as f:
        f.write(save_wml)


def export_replay(
    sim:        WesnothSim,
    source_bz2: Path,
    out_path:   Path,
    *,
    pvp_defaults: Optional[PvPDefaults] = None,
) -> None:
    """Write `out_path` (a .bz2) such that Wesnoth can load it as a
    replay reproducing `sim`'s game from its initial state.

    `source_bz2` MUST be the same replay the sim was initialized from
    (via `WesnothSim.from_replay(<json.gz>)`). The .bz2 carries the
    full scenario WML the sim's initial state was derived from --
    map, sides, factions, leader stats. We can't reconstruct that
    from the sim's GameState alone (we'd lose modifications, era
    config, ai settings, mp_era_name, etc.).

    `pvp_defaults`: when provided, rewrite the source's
    economy/experience settings to match self-play "use map settings"
    behavior. Pass the SAME `PvPDefaults` you passed to
    `WesnothSim.from_replay` so sim and Wesnoth playback agree.
    """
    source_bz2 = Path(source_bz2)
    out_path = Path(out_path)
    log.info(f"loading source replay {source_bz2}")
    # `errors="replace"` substitutes U+FFFD for malformed bytes
    # instead of dropping them. Dropping bytes (errors="ignore")
    # could shift offsets and break our [replay]-block splicing
    # silently. With "replace" we count the bad bytes via a
    # lightweight scan and warn -- a non-zero count is a signal
    # the source file is corrupted (custom-era replays sometimes
    # have stray Latin-1 bytes from old Wesnoth versions).
    with bz2.open(source_bz2, "rb") as f:
        raw = f.read()
    text = raw.decode("utf-8", errors="replace")
    n_replaced = text.count("�")
    if n_replaced:
        log.warning(
            f"{source_bz2.name}: {n_replaced} non-UTF-8 byte(s) "
            f"replaced with U+FFFD. The file may be from a "
            f"non-UTF-8 era; if Wesnoth playback errors with "
            f"'corrupt file', re-decode with errors='ignore' is "
            f"available at the call site as a fallback.")

    span = _find_final_replay_block(text)
    if span is None:
        raise RuntimeError(
            f"{source_bz2}: could not locate final [replay] block. "
            "File doesn't look like a Wesnoth replay.")
    start, end = span

    # Force oos_debug="no" in the top-level header. When the source
    # replay was saved with oos_debug="yes" (the host had "Strict
    # synchronization" enabled in the lobby), Wesnoth replaces every
    # synced command's checkup with `mp_debug_checkup`, which calls
    # `get_user_choice` against our (non-existent) `[checkup]` blocks
    # and immediately fires "expecting a user choice" on the very
    # first command -- even on a hand-built minimal trace with no
    # recruits or moves. Our exports don't emit `[checkup]` blocks,
    # so they're incompatible with debug-mode strictness; downgrading
    # to standard mode is safe and lossless for our use case.
    text = re.sub(
        r'^oos_debug=\"yes\"',
        'oos_debug="no"',
        text,
        count=1,
        flags=re.MULTILINE,
    )
    if pvp_defaults is not None:
        text = _rewrite_pvp_settings(text, pvp_defaults)
    # ALWAYS rewrite sides to match the sim's leaders / factions /
    # recruit lists. Post 2026-04-30 scenario-pool sampling, the sim
    # picks factions independently of the source replay's; without
    # this rewrite, Wesnoth's playback would instantiate the source's
    # original leaders and OOS at the first action.
    text = _rewrite_sides_for_sim(text, sim)
    span = _find_final_replay_block(text)  # re-locate after edits
    start, end = span

    new_replay = _build_replay_wml(sim.command_history)
    spliced = text[:start] + new_replay + text[end:]

    log.info(f"writing {out_path} ({len(sim.command_history)} commands)")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with bz2.open(out_path, "wt", encoding="utf-8") as f:
        f.write(spliced)


# ---------------------------------------------------------------------
# Source mapping (json.gz <-> .bz2)
# ---------------------------------------------------------------------

def find_source_bz2(json_gz_path: Path,
                    replays_raw: Path = Path("replays_raw")) -> Optional[Path]:
    """Given the path of a `replays_dataset/<id>.json.gz`, find the
    corresponding `replays_raw/<date>/<game_id>.bz2`. Returns None
    if not found (e.g., the user reorganized replays_raw)."""
    import gzip, json
    with gzip.open(json_gz_path, "rt", encoding="utf-8") as f:
        data = json.load(f)
    game_id = data.get("game_id", "")
    if not game_id:
        return None
    # game_id has double-underscore separating prefix from rest, but
    # the .bz2 filename uses the same convention. Try the literal
    # game_id first (matches recent dumps), then the legacy `_-_`
    # variant.
    candidates = [game_id + ".bz2",
                  game_id.replace("__", "_-_", 1) + ".bz2"]
    replays_raw = Path(replays_raw)
    if not replays_raw.exists():
        return None
    for date_dir in sorted(replays_raw.iterdir()):
        if not date_dir.is_dir():
            continue
        for cand in candidates:
            p = date_dir / cand
            if p.exists():
                return p
    return None


# ---------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------

def _cli(argv: List[str]) -> int:
    """`python tools/sim_to_replay.py REPLAY.json.gz OUT.bz2`
    runs a sim from REPLAY's initial state with the dummy policy and
    writes a Wesnoth-loadable replay to OUT.bz2."""
    import argparse
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    ap = argparse.ArgumentParser()
    ap.add_argument("source_json_gz", type=Path,
                    help="replays_dataset/<id>.json.gz to take init from")
    ap.add_argument("out_bz2", type=Path,
                    help="output .bz2 -- e.g., my_sim_run.bz2")
    ap.add_argument("--max-turns", type=int, default=40)
    ap.add_argument("--source-bz2", type=Path, default=None,
                    help="override automatic source-bz2 lookup")
    args = ap.parse_args(argv[1:])

    src_bz2 = args.source_bz2 or find_source_bz2(args.source_json_gz)
    if src_bz2 is None:
        log.error(
            f"could not auto-locate the .bz2 matching "
            f"{args.source_json_gz}. Pass --source-bz2 to override.")
        return 2
    log.info(f"using source bz2: {src_bz2}")

    from dummy_policy import DummyPolicy
    sim = WesnothSim.from_replay(args.source_json_gz, max_turns=args.max_turns)
    res = sim.run_game(DummyPolicy(), DummyPolicy())
    log.info(f"sim done: winner={res.winner} turns={res.turns} "
             f"ended_by={res.ended_by} "
             f"actions s1/s2 = {res.side1_actions}/{res.side2_actions}")

    export_replay(sim, source_bz2=src_bz2, out_path=args.out_bz2)
    log.info(f"wrote {args.out_bz2}")
    return 0


if __name__ == "__main__":
    sys.exit(_cli(sys.argv))
